### ISSUE TITLE
Use StringMap for Context

### ISSUE THREAD

**Issue by Tezar** [nadako/hxmustache#8]
Is there any reason why is context forced to be Dynamic? My backend uses StringMap and I am getting into serious problems making it work.  Plus I think that somthing like StringMap should be faster than using reflection. 
Was there any design decision why to use Dynamic?

**Comment by Tezar** [comment]
would you accept PR to extend Context.getfield like this ?
```
 if (Std.is(object, haxe.ds.StringMap)) {
    var map = cast(object, haxe.ds.StringMap<Dynamic>);
    return map.exists(name) ? Some(map.get(name)) : None;
}
```

**Comment by nadako** [comment]
Meh, I don't know, it was a while since I last worked on this lib and the code looks complicated... But I guess it wouldn't hurt to add StringMap support like that. One thing in that snippet that could be improved is using [unsafe cast](https://haxe.org/manual/expression-cast-unsafe.html) after the type check, or even a `Std.downcast`, since I think that would be the fastest/cleanest way.

**Comment by Tezar** [comment]
Yeah, the abstracts in the code got me little trouble since I am not much versed with them (or Haxe in general) . I have tried to make abstract accept StringMap via @from, but the default View implementation always got choosen first. Thought about rewriting it to use StringMap from base, since I am opinionated (without actually testing) about reflection but skipped the idea since it would break bc.

**Comment by nadako** [comment]
Yeah, sorry about that, this project was actually a rather quick port from js because I needed a simple and nice templating and I felt like porting+haxifying a js library at that time :)

**Comment by Tezar** [comment]
I am glad that this lib already existed. And it will motivate me to tackle abstracts sometime soon :)
